### ISSUE TITLE
Falha ao processar retorno XML do PagSeguro

### ISSUE THREAD

**Issue by lab12web** [r-martins/PagSeguro-Magento-Transparente#189]
Olá! 

Ao simular uma chamada de retorno do PagSeguro pelo Postman, ou mesmo acessando diretamente o `http://www.bottegabrasil.com.br/index.php/pseguro/notification`, eu recebo o seguinte erro:

```
Falha ao processar retorno XML do PagSeguro.

Trace:
#0 /home/bottegab/public_html/app/code/community/RicardoMartins/PagSeguro/controllers/NotificationController.php(34): Mage::throwException('Falha ao proces...')
#1 /home/bottegab/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): RicardoMartins_PagSeguro_NotificationController->indexAction()
#2 /home/bottegab/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#3 /home/bottegab/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#4 /home/bottegab/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#5 /home/bottegab/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#6 /home/bottegab/public_html/index.php(93): Mage::run('', 'store')
#7 {main}
```

No PagSeguro a notificação fica com o status HTTP 503.

Alguém teve este problema? O que pode ser?

**Comment by lab12web** [comment]
Gerei um novo token no PagSeguro e resolvi o problema.
