### ISSUE TITLE
'Zend_Serializer_Exception' with message 'vsprintf(): Too few arguments'

### ISSUE THREAD

**Issue by r-martins** [r-martins/PagSeguro-Magento-Transparente#272]
A seguinte exception é criada durante o pagamento/pedido.

> 
> exception 'Zend_Serializer_Exception' with message 'vsprintf(): Too few arguments' in ...//html/lib/Zend/Serializer/Adapter/PhpSerialize.php:90
> Stack trace:
> #0 ...//html/lib/Zend/Serializer.php(186): Zend_Serializer_Adapter_PhpSerialize->unserialize(NULL, Array)
> #1 ...//html/app/code/community/RicardoMartins/PagSeguro/Helper/Params.php(581): Zend_Serializer::unserialize(NULL)
> #2 ...//html/app/code/community/RicardoMartins/PagSeguroPro/Model/Payment/Boleto.php(30): RicardoMartins_PagSeguro_Helper_Params->getPaymentHash('sender_hash')
> #3 ...//html/app/code/core/Mage/Sales/Model/Quote/Payment.php(156): RicardoMartins_PagSeguroPro_Model_Payment_Boleto->assignData(Object(Varien_Object))

**Comment by r-martins** [comment]
O problema se dá quando o sender_hash a sessão expirou ou os dados de pagamento não foram atualizados.

**A exception não é mais exibida a partir versão 3.7.12** (1 Out 2019), quando o problema foi contornado.
